version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/qa-test
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - dependecy-cache-{{checksum "package-lock.json"}}
            - dependecy-cache
      - run:
          name: Install npm packages
          command: npm install
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Parcel build dist
          command: npm run build
      - save_cache:
          key: dependecy-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
      - store_artifacts:
          path: dist/
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy
